In [ ]:
import nltk

**bold text**

In [ ]:
corpus = "Hello my name is vishal. I am Learning NLP tutorial! I will complete the entire course."

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
from nltk.tokenize import sent_tokenize

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/movies_metadata.csv', on_bad_lines='skip', engine='python')
df.head()

   adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0

[5 rows x 24 columns]

In [ ]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [ ]:
df.shape

(45466, 24)

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(17)

In [ ]:
df = df.drop_duplicates().reset_index(drop = True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df[['original_title','genres','overview','tagline','vote_average','popularity']]
df

                    original_title  ... popularity
0                        Toy Story  ...  21.946943
1                          Jumanji  ...  17.015539
2                 Grumpier Old Men  ...    11.7129
3                Waiting to Exhale  ...   3.859495
4      Father of the Bride Part II  ...   8.387519
...                            ...  ...        ...
45444                      رگ خواب  ...   0.072051
45445          Siglo ng Pagluluwal  ...   0.178241
45446                     Betrayal  ...   0.903007
45447          Satana likuyushchiy  ...   0.003503
45448                     Queerama  ...   0.163015

[45449 rows x 6 columns]

In [ ]:
df.isnull().sum()

original_title        0
genres                0
overview            954
tagline           25042
vote_average          6
popularity            5
dtype: int64

In [ ]:
df['overview'] = df['overview'].fillna('')

In [ ]:
df['tagline'] = df['tagline'].fillna('')

In [ ]:
import ast
df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]))

In [ ]:
df.head()

                original_title  ... popularity
0                    Toy Story  ...  21.946943
1                      Jumanji  ...  17.015539
2             Grumpier Old Men  ...    11.7129
3            Waiting to Exhale  ...   3.859495
4  Father of the Bride Part II  ...   8.387519

[5 rows x 6 columns]

In [ ]:
df['tags'] = df['overview'] + df['genres'] + df['tagline']

In [ ]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
import string

In [ ]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
df.head()

                original_title  ...                                               tags
0                    Toy Story  ...  Led by Woody, Andy's toys live happily in his ...
1                      Jumanji  ...  When siblings Judy and Peter discover an encha...
2             Grumpier Old Men  ...  A family wedding reignites the ancient feud be...
3            Waiting to Exhale  ...  Cheated on, mistreated and stepped on, the wom...
4  Father of the Bride Part II  ...  Just when George Banks has recovered from his ...

[5 rows x 7 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocessing(text):
  text = str(text).lower()
  text = re.sub(r'[^\w\s]', ' ', text)
  words = text.split()
  words = [word for word in words if word not in stopwords]

  words = [lemmatizer.lemmatize(word) for word in words]
  return ' '.join(words)

In [ ]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.Animation Comedy Family"

In [ ]:
df['tags'] = df['tags'].apply(preprocessing)

In [ ]:
df['tags'][0]

'led woody andy toy live happily room andy birthday brings buzz lightyear onto scene afraid losing place andy heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

In [ ]:
df = df.reset_index(drop = True)

In [ ]:
indices  = pd.Series(df.index, index = df['original_title']).drop_duplicates()

In [ ]:
indices

original_title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
رگ خواب                        45444
Siglo ng Pagluluwal            45445
Betrayal                       45446
Satana likuyushchiy            45447
Queerama                       45448
Length: 45449, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix.shape

(45449, 50000)

In [ ]:
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

In [ ]:
def recommend(original_title, n=10):
  if original_title not in indices:
    return ["Movie not found"]
  idx = indices[original_title]
  sim_scores = linear_kernel(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_scores.argsort()[::-1][1:n+1]

  return df['original_title'].iloc[similar_idx]

In [ ]:
recommend('Avatar')

26549                                      Avatar 2
13883                              Obitaemyy Ostrov
14119                          The Three Musketeers
6414     Lara Croft Tomb Raider: The Cradle of Life
28635                             STAND BY ME ドラえもん
43434                        Moontrap: Target Earth
26555                                Thor: Ragnarok
2457                                     The Matrix
21569                         Тайна третьей планеты
29980                                     Shakedown
Name: original_title, dtype: object

In [ ]:
import pickle
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

pickle.dump(tfidf, open('tfidf.pkl', 'wb'))

pickle.dump(indices, open('indices.pkl', 'wb'))

df.to_pickle('df.pickle')